googleads/googleads-mobile-android-mediation

ThirdPartyAdapters/adcolony/CHANGELOG.md
ThirdPartyAdapters/adcolony/README.md
ThirdPartyAdapters/adcolony/adcolony/build.gradle
ThirdPartyAdapters/adcolony/adcolony/proguard-rules.pro
ThirdPartyAdapters/adcolony/adcolony/src/main/AndroidManifest.xml
ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyAdListener.java
ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyAdapter.java
ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyBundleBuilder.java
ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyManager.java
ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyReward.java
ThirdPartyAdapters/adcolony/build.gradle
ThirdPartyAdapters/adcolony/gradle.properties
ThirdPartyAdapters/adcolony/gradle/wrapper/gradle-wrapper.properties
ThirdPartyAdapters/adcolony/gradlew
ThirdPartyAdapters/adcolony/gradlew.bat
ThirdPartyAdapters/adcolony/settings.gradle

Also includes updates to CHANGELOG.md and README.md

Request to add AdColony Adapter

---

ThirdPartyAdapters/vungle/vungle/build.gradle
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java

Updated Adapter files to be compatible with Vungle SDK 5.3.0

Compatible with Vungle SDK version 5.3.0.

---

ThirdPartyAdapters/maio/maio/src/main/java/jp/maio/sdk/android/mediation/admob/adapter/Interstitial.java
ThirdPartyAdapters/maio/maio/src/main/java/jp/maio/sdk/android/mediation/admob/adapter/MaioEventForwarder.java
ThirdPartyAdapters/maio/maio/src/main/java/jp/maio/sdk/android/mediation/admob/adapter/Rewarded.java

These are the adapter files for the android adapter. 
Please advice what to do in regards to linking a maven repository and also how we can receive our ad_unit_id to test the example project.

Adding adapter files

---

ThirdPartyAdapters/mytarget/CHANGELOG.md
ThirdPartyAdapters/mytarget/mytarget/build.gradle
ThirdPartyAdapters/mytarget/mytarget/src/main/java/com/google/ads/mediation/mytarget/MyTargetNativeAdapter.java

- Added support for video and carousel ads inside MediaView
- Verified compatibility with myTarget SDK v4.7.1

Update myTarget SDK to 4.7.1

---

ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleConsent.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java

Fixed issue - Avoid setting consent to SDK if status is not set yet

Compatible with iOS SDK 6.2.0 - 2

---

ThirdPartyAdapters/adcolony/adcolony/build.gradle
ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyManager.java

Reverts googleads/googleads-mobile-android-mediation#80

Revert "Update AdColony to 3.3.4 and pass on npa info if available for GDPR purposes"

---

ThirdPartyAdapters/mytarget/mytarget/src/main/java/com/google/ads/mediation/mytarget/MyTargetNativeAdapter.java
ThirdPartyAdapters/mytarget/mytarget/src/main/java/com/google/ads/mediation/mytarget/MyTargetRewardedAdapter.java

Added MyTargetNativeUnifiedAdMapper to native adapter, and onVideoCompleted callback to rewarded adapter

Verify compatibility with Play Services 15.0.1 and myTarget SDK 5.1.0

---

ThirdPartyAdapters/vungle/CHANGELOG.md
ThirdPartyAdapters/vungle/vungle/build.gradle
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/AdapterParametersParser.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleConsent.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleExtrasBuilder.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java

- Compatible with Vungle SDK 6.3.24
- Removed all placement ID requirement for init

Compatible with Vungle SDK 6.3.24

---

ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapterBannerDelegate.java
ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapterDelegate.java
ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java

- Corrected an issue where the wrong placement was being updated in requestBannerAd()

Add Banner Support for Unity Ads

---

ThirdPartyAdapters/facebook/CHANGELOG.md
ThirdPartyAdapters/facebook/facebook/build.gradle
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookInitializer.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookMediationAdapter.java

@ericleich I force push to my fork and the old PR was closed. Sorry for the inconvenience

Updated Facebook Adapter to version 5.3.0.0

---

ThirdPartyAdapters/facebook/facebook/build.gradle
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookInitializer.java

Prepare Facebook Audience Network release 5.4.0

Release Facebook adapter 5.4.0.0

---

ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookExtras.java

Updated Facebook Adapter with Native Banner Support.

Updated Facebook Adapter with Native Banner Support.

---

ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java

Updated Ironsource adapter to remove it's lock on an instance ID in all 3 of these cases (load failed, show failed, ad closed).

Fixed Ironsource adapter to remove it's lock on an instance ID.

---

ThirdPartyAdapters/oath/oath/src/main/java/com/google/ads/mediation/verizon/AdapterInlineListener.java
ThirdPartyAdapters/oath/oath/src/main/java/com/google/ads/mediation/verizon/AdapterInterstitialListener.java
ThirdPartyAdapters/oath/oath/src/main/java/com/google/ads/mediation/verizon/ThreadUtils.java
ThirdPartyAdapters/oath/oath/src/main/java/com/google/ads/mediation/verizon/VerizonMediationAdapter.java

Added support for flexible banner ad sizes.

Added support for flexible banner ad sizes.

---

ThirdPartyAdapters/facebook/CHANGELOG.md
ThirdPartyAdapters/facebook/facebook/build.gradle

Updating Facebook Adapter to version 5.5.0.0

---

ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java

This update replaces the metadata API with a native load API.
Load() can be called before initialize(): Causes placement to load immediately on initialize()

3.2 update

---

ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityMediationAdapter.java
ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java

Fixed an issue which caused NPE while calling loadAd before calling initialize. Refactored UnitySingleton by removing static calls and static fields.

Fixed an issue which caused NPE. Refactored UnitySingleton by removing static calls and static fields. 

---

ThirdPartyAdapters/duad/duadplatform/build.gradle
ThirdPartyAdapters/duad/duadplatform/src/main/java/com/google/ads/mediation/dap/forwarder/DuNativeAdMapper.java

DuAd adapter to version1.2.8.3.0

Bumps DuAd adapter to version1.2.8.3.0

---

ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java

Fixed an issue where banners failed to refresh. Updated RelativeLayout size with MREC specific size.

Fixed an issue where vungle MREC banners failed to refresh.

---

ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/AppLovinNativeAdImage.java
ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/AppLovinNativeAdListener.java
ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/AppLovinNativeAdapter.java
ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/AppLovinUnifiedNativeAdMapper.java

Updated AppLovin Adapter with UnifiedNativeAdMapper Support and implemented mediaContentAspectRatio.

Updated AppLovin Adapter with UnifiedNativeAdMapper Support.

---

ThirdPartyAdapters/fyber/fyber/build.gradle
ThirdPartyAdapters/fyber/fyber/src/main/java/com/google/ads/mediation/fyber/FyberMediationAdapter.java
ThirdPartyAdapters/fyber/fyber/src/main/java/com/google/ads/mediation/fyber/FyberRewardedVideoRenderer.java

Fyber's Marketplace adapter for the Google AdMob mediation framework. Supports marketplace version 7.3.4 and Google Ads version 18.1.1
Banners and Interstitial are supported via the old MediationBannerAdapter and MediationInterstitialAdapter interfaces. Rewarded ads are supported via the new Adapter interface

Fyber Marketplace mediation adapter

---

ThirdPartyAdapters/mopub/mopub/src/main/java/com/mopub/mobileads/dfp/adapters/MoPubAdapter.java
ThirdPartyAdapters/mopub/mopub/src/main/java/com/mopub/mobileads/dfp/adapters/MoPubUnifiedNativeAdMapper.java

Updated MoPub Adapter with UnifiedNativeAdMapper Support and implemented mediaContentAspectRatio.

Updated MoPub Adapter with UnifiedNativeAdMapper Support.

---

ThirdPartyAdapters/fyber/build.gradle
ThirdPartyAdapters/fyber/fyber/build.gradle
ThirdPartyAdapters/fyber/fyber/src/main/java/com/google/ads/mediation/fyber/FyberMediationAdapter.java
ThirdPartyAdapters/fyber/fyber/src/main/java/com/google/ads/mediation/fyber/FyberRewardedVideoRenderer.java

Certifying Fyber Android adapter.

Certifying Fyber Android adapter.

---

ThirdPartyAdapters/fyber/CHANGELOG.md
ThirdPartyAdapters/fyber/fyber/build.gradle
ThirdPartyAdapters/fyber/fyber/src/main/java/com/google/ads/mediation/fyber/FyberMediationAdapter.java

Verified compatibility with Fyber SDK 7.5.0

Verified compatibility with Fyber SDK 7.5.0

---

ThirdPartyAdapters/facebook/CHANGELOG.md
ThirdPartyAdapters/facebook/facebook/build.gradle

Updated for AN SDK 5.7.0

---

ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/rtb/FacebookRtbNativeAd.java

Add native banner support for v5.7.0.0

Add native banner support for v5.7.0.0

---

ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookMediationAdapter.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookRewardedAd.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/rtb/FacebookRtbBannerAd.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/rtb/FacebookRtbInterstitialAd.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/rtb/FacebookRtbNativeAd.java

Standardize how 3p adapter and 3p SDK error codes and descriptions are sent to the GMA SDK.

Standardize how 3p adapter and 3p SDK error codes and descriptions are sent to the GMA SDK.

---

ThirdPartyAdapters/fyber/CHANGELOG.md
ThirdPartyAdapters/fyber/fyber/build.gradle

Verified Fyber Marketplace Android adapter compatibility with Fyber Marketplace SDK version 7.5.2

Verified Fyber Marketplace Android adapter compatibility with Fyber Marketplace SDK version 7.5.2

---

ThirdPartyAdapters/facebook/CHANGELOG.md
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookMediationAdapter.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookRewardedAd.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/rtb/FacebookRtbBannerAd.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/rtb/FacebookRtbInterstitialAd.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/rtb/FacebookRtbNativeAd.java

update error codes for version 5.8.0.1

update error codes for version 5.8.0.1

---

ThirdPartyAdapters/unity/CHANGELOG.md
ThirdPartyAdapters/unity/unity/build.gradle
ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapterDelegate.java
ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdsAdapterUtils.java
ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityMediationAdapter.java
ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java

Added descriptive error codes and reasons for Unity Ads Android adapter load/show failures.

Added descriptive error codes and reasons for Unity Ads Android adapter load/show failures.

---

ThirdPartyAdapters/facebook/CHANGELOG.md
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookMediationAdapter.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookRewardedAd.java
ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookRewardedInterstitialAd.java

Updated Facebook Android adapter to support rewarded interstitial ads

Updated Facebook Android adapter to support rewarded interstitial ads

---

ThirdPartyAdapters/nend/CHANGELOG.md
ThirdPartyAdapters/nend/nend/src/main/java/com/google/ads/mediation/nend/NendAdapter.java

Updated nend Android adapter based on internal review.
Main change is that we always add a wrapper view, so there is no longer a need for the global receiver.

Updated nend Android adapter based on internal review.

---

ThirdPartyAdapters/applovin/CHANGELOG.md
ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/AppLovinInterstitialAdListener.java
ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/AppLovinNativeAdListener.java
ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/AppLovinUtils.java
ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/ApplovinAdapter.java
ThirdPartyAdapters/applovin/applovin/src/main/java/com/google/ads/mediation/applovin/AppLovinMediationAdapter.java

Updated AppLovin Android adapter to prevent loading of non open-bidding interstitial ads using the same Zone ID.

Updated AppLovin Android adapter to prevent loading of non open-bidding interstitial ads using the same Zone ID.

---

ThirdPartyAdapters/vungle/CHANGELOG.md
ThirdPartyAdapters/vungle/vungle/build.gradle
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleExtrasBuilder.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java

Updating Vungle Android adapter based on internal review.

Updating Vungle Android adapter based on internal review.

---

ThirdPartyAdapters/fyber/fyber/build.gradle
ThirdPartyAdapters/fyber/fyber/src/main/java/com/google/ads/mediation/fyber/FyberRewardedVideoRenderer.java

+ Supported Fyber Marketplace version updated to v7.6.0
+ Add the new rewarded callback support - reward callback for both video and display reward ads

update Fyber Admob adapter to support Fyber Marketplace version 7.6.0

---

ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapter.java
ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterListener.java
ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceManager.java
ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java

Removed instance state from the IronSource Android adapter.

Removed instance state from the IronSource Android adapter.

---

ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java

Refactored Vungle Android adapter to separate Banner implementation

Refactored Vungle Android adapter to separate Banner implementation

---

ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/rtb/AppLovinRtbBannerRenderer.java

Remove banner size checks for AppLovin OB

Remove banner size checks for AppLovin OB

---

ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityRewardedAd.java

In mPlacementsInUse hashmap, it should use reference check to avoid cases like request timeout

Fix reference check for mPlacementsInUse hashmap

---

ThirdPartyAdapters/vungle/build.gradle
ThirdPartyAdapters/vungle/gradle/wrapper/gradle-wrapper.properties
ThirdPartyAdapters/vungle/vungle/build.gradle
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleBannerAd.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VunglePlayAdCallback.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleListener.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java

Refactored VungleManager class to remove strong reference to the adapter in a HashMap

Refactored VungleManager class to remove strong reference to the adapter in a HashMap

---

ThirdPartyAdapters/mytarget/mytarget/build.gradle
ThirdPartyAdapters/mytarget/mytarget/src/main/java/com/google/ads/mediation/mytarget/MyTargetNativeAdapter.java

This version is available on jcenter and mavenCentral, since next version we will host MyTarget library in mavenCentral() only

Bump MyTarget to 5.11.12, specify MediaAdView to register in NativeAds adapter

---

ThirdPartyAdapters/ironsource/CHANGELOG.md
ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java

Updated IronSource Android adapter to add support for rewarded interstitial ads

Updated IronSource Android adapter to add support for rewarded interstitial ads

---

ThirdPartyAdapters/vungle/CHANGELOG.md
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/AdapterParametersParser.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleNetworkSettings.java

Update of error codes and messages for Vungle Android Adapter.

Update of error codes and messages for Vungle Android Adapter.

---

ThirdPartyAdapters/vungle/CHANGELOG.md
ThirdPartyAdapters/vungle/build.gradle
ThirdPartyAdapters/vungle/vungle/build.gradle
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleBannerAd.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VunglePlayAdCallback.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleNetworkSettings.java

- Verified compatibility with Vungle SDK 6.10.1.
- Render MREC ads with Banner API supported.
- Use standard AdError code and messages.

Vungle mediation adapter 6.10.1.0 release

---

ThirdPartyAdapters/vungle/CHANGELOG.md
ThirdPartyAdapters/vungle/vungle/build.gradle
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAd.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbInterstitialAd.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/AdapterParametersParser.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java

Vungle adapter 6.10.2 release

---

ThirdPartyAdapters/dtexchange/dtexchange/src/main/java/com/google/ads/mediation/fyber/FyberAdapterUtils.java
ThirdPartyAdapters/dtexchange/dtexchange/src/main/java/com/google/ads/mediation/fyber/FyberMediationAdapter.java
ThirdPartyAdapters/dtexchange/dtexchange/src/main/java/com/google/ads/mediation/fyber/FyberRewardedVideoRenderer.java

Example usage (kt) -
```
addNetworkExtrasBundle(FyberMediationAdapter::class.java, Bundle().apply {
putBoolean("muteVideo", true)
})
```

[DT Exchange] Added an optional route for publishers mute interstitials

---

ThirdPartyAdapters/adaptertestkit/build.gradle
ThirdPartyAdapters/adaptertestkit/src/main/java/com/google/ads/mediation/adaptertestkit/AdapterTestKit.kt
ThirdPartyAdapters/mintegral/build.gradle
ThirdPartyAdapters/mintegral/mintegral/build.gradle
ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralFactory.kt
ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralMediationAdapter.java
ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/mediation/MintegralAppOpenAd.java
ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/waterfall/MintegralWaterfallAppOpenAd.java
ThirdPartyAdapters/mintegral/mintegral/src/test/java/com/google/ads/mediation/mintegral/MintegralMediationAdapterTest.kt
ThirdPartyAdapters/mintegral/mintegral/src/test/java/com/google/ads/mediation/mintegral/MintegralWaterfallAppOpenAdTest.kt
ThirdPartyAdapters/mintegral/settings.gradle

Implements Mintegral's Splash Ads for waterfall as GMA AppOpen ads

Implements Mintegral's Splash Ads for waterfall as GMA AppOpen ads

---

ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceBannerAd.java

Remove IronSource duplicated load banner

Remove duplicated load banner

---

ThirdPartyAdapters/adaptertestkit/src/main/java/com/google/ads/mediation/adaptertestkit/AdapterTestKit.kt
ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/MintegralFactory.kt
ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbAppOpenAd.java
ThirdPartyAdapters/mintegral/mintegral/src/test/java/com/google/ads/mediation/mintegral/MintegralMediationAdapterTest.kt

Invocation of the AppOpen watermark for bidding in Mintegral adapter

Invocation of the AppOpen watermark for bidding in Mintegral adapter

---

ThirdPartyAdapters/ironsource/CHANGELOG.md
ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceConstants.java
ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceMediationAdapter.java
ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRewardedAd.java
ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceMediationAdapterTest.kt
ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceRewardedAdTest.kt

Updating IronSource adapter to support RTB ads.

Updating ironSource adapter to support RTB ads.

---

ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceAdapterUtils.java
ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceInterstitialAd.java
ThirdPartyAdapters/ironsource/ironsource/src/main/java/com/google/ads/mediation/ironsource/IronSourceRewardedAd.java
ThirdPartyAdapters/ironsource/ironsource/src/test/kotlin/com/google/ads/mediation/ironsource/IronSourceMediationAdapterTest.kt

Updating adapter to pass watermark to IronSource SDK.

Updating adapter to pass watermark to IronSource SDK.

---

ThirdPartyAdapters/line/line/build.gradle
ThirdPartyAdapters/line/line/src/main/java/com/google/ads/mediation/line/LineMediationAdapter.kt
ThirdPartyAdapters/line/line/src/test/java/com/google/ads/mediation/line/LineMediationAdapterTest.kt
ThirdPartyAdapters/line/settings.gradle

Implement collectSignals for Line Mediation Adapter.

Implement collectSignals for Line Mediation Adapter.

---

ThirdPartyAdapters/line/CHANGELOG.md
ThirdPartyAdapters/line/line/src/main/java/com/google/ads/mediation/line/LineMediationAdapter.kt
ThirdPartyAdapters/line/line/src/main/java/com/google/ads/mediation/line/LineRewardedAd.kt
ThirdPartyAdapters/line/line/src/test/java/com/google/ads/mediation/line/LineMediationAdapterTest.kt
ThirdPartyAdapters/line/line/src/test/java/com/google/ads/mediation/line/LineRewardedAdTest.kt

Implement RTB for Line Rewarded Ads.

Implement RTB for Line Interstitial and Rewarded Ads.

---

ThirdPartyAdapters/line/CHANGELOG.md
ThirdPartyAdapters/line/line/src/main/java/com/google/ads/mediation/line/LineBannerAd.kt
ThirdPartyAdapters/line/line/src/main/java/com/google/ads/mediation/line/LineMediationAdapter.kt
ThirdPartyAdapters/line/line/src/test/java/com/google/ads/mediation/line/LineBannerAdTest.kt
ThirdPartyAdapters/line/line/src/test/java/com/google/ads/mediation/line/LineMediationAdapterTest.kt

Implement RTB Banner Ad loading for Line Mediation Adapter.

Implement RTB Banner Ad loading for Line Mediation Adapter.

---

ThirdPartyAdapters/line/CHANGELOG.md
ThirdPartyAdapters/line/line/src/main/java/com/google/ads/mediation/line/LineMediationAdapter.kt
ThirdPartyAdapters/line/line/src/main/java/com/google/ads/mediation/line/LineNativeAd.kt
ThirdPartyAdapters/line/line/src/test/java/com/google/ads/mediation/line/LineMediationAdapterTest.kt
ThirdPartyAdapters/line/line/src/test/java/com/google/ads/mediation/line/LineNativeAdTest.kt

Implement RTB Native Ad loading for Line Mediation Adapter.

Implement RTB Native Ad loading for Line Mediation Adapter.

---

ThirdPartyAdapters/liftoffmonetize/CHANGELOG.md
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/build.gradle
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/VungleInitializerTest.kt
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/VungleMediationAdapterTest.kt
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/VungleRewardedAdTest.kt
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/rtb/VungleRtbAppOpenAdTest.kt
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAdTest.kt
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/rtb/VungleRtbInterstitialAdTest.kt
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/rtb/VungleRtbNativeAdTest.kt
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/rtb/VungleRtbRewardedAdTest.kt
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/waterfall/VungleWaterfallAppOpenAdTest.kt

Vungle 7.4.3 adapter release

---

ThirdPartyAdapters/line/CHANGELOG.md
ThirdPartyAdapters/line/line/src/main/java/com/google/ads/mediation/line/LineInterstitialAd.kt
ThirdPartyAdapters/line/line/src/main/java/com/google/ads/mediation/line/LineMediationAdapter.kt
ThirdPartyAdapters/line/line/src/main/java/com/google/ads/mediation/line/LineRewardedAd.kt
ThirdPartyAdapters/line/line/src/main/java/com/google/ads/mediation/line/LineSdkFactory.kt
ThirdPartyAdapters/line/line/src/test/java/com/google/ads/mediation/line/LineMediationAdapterTest.kt

#LINE #Android #Adapter Use context instead of activity for loading ads.

#LINE #Android #Adapter Use context instead of activity for loading ads.

---

ThirdPartyAdapters/dtexchange/dtexchange/src/main/java/com/google/ads/mediation/fyber/FyberMediationAdapter.java
ThirdPartyAdapters/dtexchange/dtexchange/src/main/java/com/google/ads/mediation/fyber/FyberRewardedVideoRenderer.java
ThirdPartyAdapters/dtexchange/dtexchange/src/test/kotlin/com/google/ads/mediation/fyber/FyberMediationAdapterTest.kt
ThirdPartyAdapters/dtexchange/dtexchange/src/test/kotlin/com/google/ads/mediation/fyber/FyberRewardedVideoRendererTest.kt

Added RTB implementation for DTExchange:
* Adds new classes for Banner and Interstitial to handle the SDK bidding
* Adds RTB bidding functionality for Rewarded Ads

Added RTB implementation for DTExchange

---

ThirdPartyAdapters/bidmachine/bidmachine/src/main/kotlin/com/google/ads/mediation/bidmachine/BidMachineMediationAdapter.kt
ThirdPartyAdapters/bidmachine/bidmachine/src/main/kotlin/com/google/ads/mediation/bidmachine/BidMachineNativeAd.kt
ThirdPartyAdapters/bidmachine/bidmachine/src/test/kotlin/com/google/ads/mediation/bidmachine/BidMachineNativeAdTest.kt

Adds implementation of BidMachine Mediation Adapter for SDK bidding.

BidMachine Adapter for Banner, Interstitial, Rewarded and Native Ads.

---

ThirdPartyAdapters/pubmatic/pubmatic/src/main/AndroidManifest.xml
ThirdPartyAdapters/pubmatic/pubmatic/src/main/kotlin/com/google/ads/mediation/pubmatic/PubMaticAdFactory.kt
ThirdPartyAdapters/pubmatic/pubmatic/src/main/kotlin/com/google/ads/mediation/pubmatic/PubMaticAdFactoryImpl.kt
ThirdPartyAdapters/pubmatic/pubmatic/src/main/kotlin/com/google/ads/mediation/pubmatic/PubMaticBannerAd.kt
ThirdPartyAdapters/pubmatic/pubmatic/src/main/kotlin/com/google/ads/mediation/pubmatic/PubMaticMediationAdapter.kt
ThirdPartyAdapters/pubmatic/pubmatic/src/test/kotlin/com/google/ads/mediation/pubmatic/PubMaticBannerAdTests.kt
ThirdPartyAdapters/pubmatic/pubmatic/src/test/kotlin/com/google/ads/mediation/pubmatic/PubMaticMediationAdapterTest.kt

#PubMaticAdapter Implement initialization, signal collection, banner, interstitial and rewarded ads.

#PubMaticAdapter Implement initialization, signal collection, banner, interstitial and rewarded ads.

---

ThirdPartyAdapters/pubmatic/CHANGELOG.md
ThirdPartyAdapters/pubmatic/pubmatic/build.gradle
ThirdPartyAdapters/pubmatic/pubmatic/src/main/kotlin/com/google/ads/mediation/pubmatic/PubMaticAdFactory.kt
ThirdPartyAdapters/pubmatic/pubmatic/src/main/kotlin/com/google/ads/mediation/pubmatic/PubMaticAdFactoryImpl.kt
ThirdPartyAdapters/pubmatic/pubmatic/src/main/kotlin/com/google/ads/mediation/pubmatic/PubMaticMediationAdapter.kt
ThirdPartyAdapters/pubmatic/pubmatic/src/main/kotlin/com/google/ads/mediation/pubmatic/PubMaticNativeAd.kt
ThirdPartyAdapters/pubmatic/pubmatic/src/test/kotlin/com/google/ads/mediation/pubmatic/PubMaticMediationAdapterTest.kt
ThirdPartyAdapters/pubmatic/pubmatic/src/test/kotlin/com/google/ads/mediation/pubmatic/PubMaticNativeAdTests.kt

#PubMaticAdapter #Android Implement native ad.

#PubMaticAdapter #Android Implement native ad.

---

ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAd.java
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/VungleMediationAdapterTest.kt
ThirdPartyAdapters/liftoffmonetize/liftoffmonetize/src/test/java/com/google/ads/mediation/vungle/rtb/VungleRtbBannerAdTest.kt

Remove the bannerLayout and return our bannerAdView directly. Google AdView can layout it correctly.

[Liftoff] Bug fix: impression discrepancy

---

.github/workflows/example.yaml
Example/settings.gradle
Example/snippets/build.gradle
Example/snippets/proguard-rules.pro
Example/snippets/src/main/AndroidManifest.xml
Example/snippets/src/main/java/com/google/ads/mediation/snippets/java/AppLovinMediationSnippets.java

Add GitHub workflow for mediation example CI/CD.

Add GitHub workflow for mediation example CI/CD.
