- ThirdPartyAdapters/mopub/mopub/src/main/java/com/mopub/mobileads/dfp/adapters/MoPubAdapter.java
- ThirdPartyAdapters/mopub/mopub/src/main/java/com/mopub/mobileads/dfp/adapters/MoPubNativeAppInstallAdMapper.java
- ThirdPartyAdapters/mopub/mopub/src/main/java/com/mopub/mobileads/dfp/adapters/MoPubNativeMappedImage.java
Adding additional try/catch clauses around code blocks that can throw exceptions when certain assets from MoPub are null / not present during parsing.
> Catching NPEs if null image URLs

- ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyAdListener.java
- ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyAdapter.java
- ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyManager.java
- ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyReward.java
These changes are in direct response to issues reported to AdColony support by some publishers. An overview of the changes split by issue:
1. When our adapter is destroyed in an app session we drop the Context reference held by AdColonyManager as to not leak. As initialize() is only called once, this leaves us in a state where our instanceof Activity check fails in AdColonyManager's configureAdColony() if a new adapter instance is used later to request ads. Allowing a null context is fine in this case because AdColony has already been configured.
2. Along the same lines, publishers were running into scenarios where when destroying and reinitializing the adapter they are sometimes struggling to get filled ad requests from us. Introducing an idea of request state via the RequestState enum …
> Adding fixes for bugs reported by publishers during 3.3.0 development

- ThirdPartyAdapters/mopub/mopub/build.gradle
- ThirdPartyAdapters/mopub/mopub/src/main/java/com/mopub/mobileads/dfp/adapters/MoPubAdapter.java
* As of MoPub 5.0.0, keywords needed to be separate into two APIs based on whether they contain personally identifiable information.
* Initialize the MoPub SDK in the adapter with a valid ad unit ID from the publisher's app.
> Separate keywords passing + Initialize MoPub

- ThirdPartyAdapters/adcolony/adcolony/build.gradle
- ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyBundleBuilder.java
- ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyManager.java
Now collecting consent via AdColonyBundleBuilder instead of forwarding AdMob "npa" string as discussed in this revert: https://github.com/googleads/googleads-mobile-android-mediation/pull/82
> Bump version to 3.3.4, pass GDPR consent to AdColony

- ThirdPartyAdapters/mopub/CHANGELOG.md
- ThirdPartyAdapters/mopub/mopub/src/main/java/com/mopub/mobileads/dfp/adapters/MoPubAdapter.java
This is helpful for publishers who do not already initialize MoPub in their apps. In that scenario, starting in MoPub 5.2.0, ad requests are canceled. The adapters will check for initialization status first, and will initialize MoPub manually in the adapter and retry the ad requests on the publisher's behalf. This PR ensures that all ad requests to MoPub will go through.
> Initialize MoPub manually

- ThirdPartyAdapters/facebook/CHANGELOG.md
- ThirdPartyAdapters/facebook/facebook/build.gradle
- ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java
Preparing adapter for Facebook Audience Network 5.2.0. This adapter works with the Beta SDK which can be downloaded from https://developers.facebook.com/docs/audience-network/sdk-beta-program.
This PR includes:
*  NativeAdsAttributes mapping has been removed as they were not sent from the server. FAN SDK 5.2.0 has deprecated these attributes.
* Added NativeAdLayout to Native Ads views with a FrameLayout as parent..
* Bumping up adapter version.
> Updated Facebook Audience Network Adapter to version 5.2.0

- ThirdPartyAdapters/adcolony/adcolony/build.gradle
- ThirdPartyAdapters/adcolony/adcolony/src/main/java/com/jirbo/adcolony/AdColonyManager.java
AdColony v3.3.6 added support for Application in addition to Activity in configure(), so I've altered both the instanceof checks and the calls to configure() to be aware of this.
Additionally, there were changes made to the setAppOptions() and configure() logic [in this commit](https://github.com/googleads/googleads-mobile-android-mediation/commit/a79ea4730a7cf1d418d3eaf6e61f022df787fa2a#diff-ef1d9c56d259f438a1f3eff6ca4b2091R77) (look around line 77 in AdColonyManager.java).
The problem with this is twofold, both of which I have made changes around:
1. The AdColony API is not available until after configure(), so setAppOptions() is designed in a way to be used only if AppOptions has changed at runtime, post-configuration - otherwise the object can just be passed into the configure() call. …
> Context and AppOptions Changes for AdColony Adapter

- ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnitySingleton.java
Changes:
- Load API functionality added via metadata API
- Improved diagnostics
Notes:
Load API will prevent rewarded and interstitial placements from loading in UnityAds until load is called.
To enable load API: enable_metadata_load must be set, and the game ID must be whitelisted by UnityAds.
If load API is not enabled, metadata calls should not affect on the adapter's behavior.
> Adapter 3.1 update

- ThirdPartyAdapters/facebook/facebook/src/main/java/com/google/ads/mediation/facebook/FacebookAdapter.java
FacebookAdapter uses a deprecated size 320x50 and FAN not is not filling requests mapped to this size. Banner unit's width is flexible and the view will use the provided space.
> Fixed Facebook banner mapping using 320x50

- ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/AppLovinUtils.java
- ThirdPartyAdapters/applovin/applovin/src/main/java/com/applovin/mediation/ApplovinAdapter.java
- ThirdPartyAdapters/applovin/applovin/src/main/java/com/google/ads/mediation/applovin/AppLovinMediationAdapter.java
AppLovin deprecated placements and the usages are already removed, but these logs and such still remain.
> Remove references to placement in AppLovin adapter

- ThirdPartyAdapters/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleExtrasBuilder.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleListener.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
1. Verified compatibility with Vungle SDK 6.7.0.
2. Fetch and merge AdMob latest master source code.
3. Ad playback callback changes: support adClick, adLeftApplication, etc.
4. Workaround banner leak when AdMob destroy method not invoked correctly.
5. Fix bugs: unmute fullscreen ads by default except for banner/MREC.
> Release Vungle 6.7.0 adapter

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
Updating Vungle from 6.7.0 to 6.7.1
Adding back in line removed from:
https://github.com/googleads/googleads-mobile-android-mediation/commit/28738e9f2b9fc446f1f95587a2135e7504c5b1a0#diff-c1f0849a50e777b58a3b95dffff4041cL159
> Vungle update to version 6.7.1

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleBannerAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleManager.java
Updating Vungle Admob Adapter to support Vungle 6.8.1
Currently onAdViewed is not mapped to any mediation callbacks so there are no changes in adapter callback behavior compared to the previous release.
> Upgrading to Vungle 6.8.1

- ThirdPartyAdapters/chartboost/chartboost/src/main/java/com/google/ads/mediation/chartboost/ChartboostSingleton.java
You could miss the callback if you set the delegate after the network initialization.
> fix: move setDelegate to avoid missing Chartboost network initialization callback

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
**Update to Latest Vungle 6.10.2**
Adapter rebuilt with Vungle's SDK V6.10.2
**Change Log:**
- Fix adapter issue with passing of the Unique ID to help  with concurrent Banner request for same Banner AdUnit. 
This was broken since re-work around error handling
- Fix for low occurring ConcurrentModificationException crash in Vungle’s SDK
> Vungle Adapter Update to 6.10.2

- ThirdPartyAdapters/vungle/CHANGELOG.md
- ThirdPartyAdapters/vungle/vungle/build.gradle
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleInitializer.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/google/ads/mediation/vungle/VungleMediationAdapter.java
- ThirdPartyAdapters/vungle/vungle/src/main/java/com/vungle/mediation/VungleInterstitialAdapter.java
- Verified compatibility with Vungle SDK 6.10.3.
- Added support for Child-Directed setting (COPPA) to be pass to the Vungle SDK via new API
Built and tested with:
- Google Mobile Ads SDK version 20.5.0.
- Vungle SDK version 6.10.3.
> Updating Vungle to 6.10.3

- ThirdPartyAdapters/nend/nend/src/main/java/com/google/ads/mediation/nend/NativeAdLoader.java
NendAdLoader  has typo . fix that.
fix this [issue #378 ](https://github.com/googleads/googleads-mobile-android-mediation/issues/378).
> fix NendAdLoader typo nendLogoImage to nendAdImage

- ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityAdapter.java
- ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityBannerAd.java
- ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityRewardedAd.java
To improve fill expectation issues, enhance tracking and provide sequential caching, we must add Object ID to load and show request of an Ad Unit.
This PR is to add a UUID when issuing Load request and use the same (as object ID) when doing the Show call later.
Manually tested in Waterfall that we send Load and Show options as expected in the adapter.
> [UnityAds] Add objectId for all Load/Show API calls

- ThirdPartyAdapters/chartboost/build.gradle
- ThirdPartyAdapters/chartboost/chartboost/build.gradle
Latest version of CB SDK 9.3.0. Doesn't contain any breaking changes but requires
maven {
url 'https://cboost.jfrog.io/artifactory/chartboost-ads/'
}
repository to be added in the gradle to access the sdk.
> Update Chartboost sdk to version 9.3.0

- ThirdPartyAdapters/mintegral/mintegral/build.gradle
- ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbBannerAd.java
- ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbInterstitialAd.java
- ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
- ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbRewardedAd.java
- ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/waterfall/MintegralWaterfallBannerAd.java
- ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/waterfall/MintegralWaterfallInterstitialAd.java
- ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/waterfall/MintegralWaterfallNativeAd.java
- ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/waterfall/MintegralWaterfallRewardedAd.java
Now there are two questions,
1. MTG's SDK is expected to be available from Maven warehouse in 24 hours
2. Is the usage of native correct. We internally process the view parameter in `trackViews(@NonNull View view, @NonNull Map<String, View> clickableAssetViews,
@NonNull Map<String, View> map1) ` as a FrameLayout and set the size of the watermark image using the size of the view.
> support watermark

- ThirdPartyAdapters/unity/unity/src/main/java/com/google/ads/mediation/unity/UnityBannerAd.java
Fix a rare case where the Mediation level banner is destroyed before receiving banner callbacks from Unity Ads.
> Fix NPE case where destroy() was called before BannerView callback happens.

- ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/mediation/MintegralNativeAd.java
- ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/mediation/MintegralNativeAdListener.java
- ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/rtb/MintegralRtbNativeAd.java
- ThirdPartyAdapters/mintegral/mintegral/src/main/java/com/google/ads/mediation/mintegral/waterfall/MintegralWaterfallNativeAd.java
In previous versions, due to our failure to handle a series of callbacks related to MBMediaView, events could not be given to the admob sdk through the adapter when interacting with users and MBMediaView.
We have set up listening for MBMediaView this time and also addressed the issue of whether nativeCallback can only have value after the load is completed
> support mediaview of native view clickable

- ThirdPartyAdapters/moloco/CHANGELOG.md
- ThirdPartyAdapters/moloco/gradle.properties
- ThirdPartyAdapters/moloco/gradlew.bat
- ThirdPartyAdapters/moloco/moloco/src/main/kotlin/com/google/ads/mediation/moloco/MolocoMediationAdapter.kt
- ThirdPartyAdapters/moloco/moloco/src/test/kotlin/com/google/ads/mediation/moloco/MolocoMediationAdapterTest.kt
#Moloco #Adapter Fix the mediation platform name that is set when initializing Moloco SDK.
> #Moloco #Adapter Fix the mediation platform name that is set when initializing Moloco SDK.
